// <auto-generated />
using System;
using ArrnowConstruct.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArrnowConstruct.Infrastructure.Migrations
{
    [DbContext(typeof(ArrnowConstructDbContext))]
    [Migration("20221217224644_SeedDatabaseigration")]
    partial class SeedDatabaseigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bathroom"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 4,
                            Name = "LivingRoom"
                        },
                        new
                        {
                            Id = 5,
                            Name = "DiningRoom"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hall"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Office"
                        },
                        new
                        {
                            Id = 8,
                            Name = "GameRoom"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pantry"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Toilet"
                        },
                        new
                        {
                            Id = 11,
                            Name = "UtilityRoom"
                        },
                        new
                        {
                            Id = 12,
                            Name = "SpareRoom"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Cellar"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Attic"
                        });
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            UserId = "babdaf39-3545-48e1-877e-13d4bb4d597f"
                        });
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Constructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Constructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Salary = 1500m,
                            UserId = "7125d323-7567-4f56-b27e-6b7044014a37"
                        });
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UrlPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConstructorId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConstructorId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(169)
                        .HasColumnType("nvarchar(169)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("nvarchar(56)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "babdaf39-3545-48e1-877e-13d4bb4d597f",
                            AccessFailedCount = 0,
                            Address = "Graf Ignatiev 6 ",
                            City = "Kazanlak",
                            ConcurrencyStamp = "798e8196-40fe-480b-91e0-b9ccfa1e1e24",
                            Country = "Bulgaria",
                            Email = "gogi@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Gogi",
                            IsActive = true,
                            LastName = "Milkov",
                            LockoutEnabled = false,
                            NormalizedEmail = "GOGI@GMAIL.COM",
                            NormalizedUserName = "GOGI",
                            PasswordHash = "AQAAAAEAACcQAAAAELtJPh9gHdXWPnXziq5k/6VFbGngNAQi6B1q9rTlA3sm9lqplwU3Ekh51E1DeO65Uw==",
                            PhoneNumber = "0886121261",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "http://res.cloudinary.com/dmv8nabul/image/upload/v1671315120/images/tfcjhrtonc17iox0yoel.png",
                            SecurityStamp = "92844926-829f-4fb3-9be0-86ae9cec786b",
                            TwoFactorEnabled = false,
                            UserName = "gogi"
                        },
                        new
                        {
                            Id = "ae724eb3-355b-48dd-bdaa-c1eaccf666c5",
                            AccessFailedCount = 0,
                            Address = "Edelvais 6 ",
                            City = "Kazanlak",
                            ConcurrencyStamp = "1d61081d-e700-437d-aefc-c7bf6e0541f9",
                            Country = "Bulgaria",
                            Email = "kresa@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Kresa",
                            IsActive = true,
                            LastName = "Tsvetkova",
                            LockoutEnabled = false,
                            NormalizedEmail = "KRESA@MAIL.COM",
                            NormalizedUserName = "KRESA",
                            PasswordHash = "AQAAAAEAACcQAAAAEItR/AijuGtbdJTwdg5n+wI0BMEJ7tsJH9NL9CkB5mlpLg5n4nULl14gBwemAM7wRw==",
                            PhoneNumber = "0886121260",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "http://res.cloudinary.com/dmv8nabul/image/upload/v1671315197/images/sayxo7gbosyd1w5xd72r.png",
                            SecurityStamp = "b92e1350-22eb-4f83-bfad-cdbd336507b9",
                            TwoFactorEnabled = false,
                            UserName = "kresa"
                        },
                        new
                        {
                            Id = "7125d323-7567-4f56-b27e-6b7044014a37",
                            AccessFailedCount = 0,
                            Address = "Petko DePetkov 71",
                            City = "Kazanlak",
                            ConcurrencyStamp = "8d9d5b9b-9c07-440e-aca2-cfdcf0da291a",
                            Country = "Bulgaria",
                            Email = "angel@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Angel",
                            IsActive = true,
                            LastName = "Momov",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANGEL@GMAIL.COM",
                            NormalizedUserName = "ANGEL",
                            PasswordHash = "AQAAAAEAACcQAAAAEDsTi2R46F8/sJmht7z9RFtgCM0MvGlgiokNAmapjqJIiA9oS4FFRT7nKBA7VQyj1A==",
                            PhoneNumber = "0888791001",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "http://res.cloudinary.com/dmv8nabul/image/upload/v1671314968/images/vymjt1vk8itzucplowxg.png",
                            SecurityStamp = "49093e46-c875-42a6-8faf-4b0500d189af",
                            TwoFactorEnabled = false,
                            UserName = "angel"
                        });
                });

            modelBuilder.Entity("CategoryRequest", b =>
                {
                    b.Property<int>("RequestsId")
                        .HasColumnType("int");

                    b.Property<int>("RoomsTypesId")
                        .HasColumnType("int");

                    b.HasKey("RequestsId", "RoomsTypesId");

                    b.HasIndex("RoomsTypesId");

                    b.ToTable("CategoryRequest");
                });

            modelBuilder.Entity("CategorySite", b =>
                {
                    b.Property<int>("RoomsTypesId")
                        .HasColumnType("int");

                    b.Property<int>("SitesId")
                        .HasColumnType("int");

                    b.HasKey("RoomsTypesId", "SitesId");

                    b.HasIndex("SitesId");

                    b.ToTable("CategorySite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4033acf9-98f0-49e3-aafc-fd4fcb71c67e",
                            ConcurrencyStamp = "0d76fbc8-8c8f-4ef8-9324-8543039cf95d",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "25f73449-f9e8-40b4-87ee-93fc6c242339",
                            ConcurrencyStamp = "5b928bfd-04c6-4f29-ba14-c845d6cb9e72",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = "eed2d778-89cf-4c3c-a710-c8d61811f4c7",
                            ConcurrencyStamp = "c1b75fde-3fdd-4b56-8a11-7e246d03f1b8",
                            Name = "Constructor",
                            NormalizedName = "CONSTRUCTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "babdaf39-3545-48e1-877e-13d4bb4d597f",
                            RoleId = "25f73449-f9e8-40b4-87ee-93fc6c242339"
                        },
                        new
                        {
                            UserId = "ae724eb3-355b-48dd-bdaa-c1eaccf666c5",
                            RoleId = "4033acf9-98f0-49e3-aafc-fd4fcb71c67e"
                        },
                        new
                        {
                            UserId = "7125d323-7567-4f56-b27e-6b7044014a37",
                            RoleId = "eed2d778-89cf-4c3c-a710-c8d61811f4c7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Client", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Constructor", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Image", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Post", "Post")
                        .WithMany("Image")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Post", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Request", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Client", "Client")
                        .WithMany("Requests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Constructor", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Site", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Constructor", "Constructor")
                        .WithMany("Sites")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("CategoryRequest", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("RoomsTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategorySite", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("RoomsTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.Site", null)
                        .WithMany()
                        .HasForeignKey("SitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ArrnowConstruct.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Client", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Constructor", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("ArrnowConstruct.Infrastructure.Data.Entities.Post", b =>
                {
                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
